name: Skream
version: '${project.version}'
main: us.happypockets.skream.Skream
api-version: 1.16
depend: [ Skript ]
softdepend: [ Citizens, LuckPerms ]
authors: [ hapily, hotpocket184 ]
description: Placeholder
website: https://github.com/hapily04/Skream
